# Generated by Django 4.1 on 2022-08-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_appuser_ec_status_appuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='user_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='phone_no',
            field=models.CharField(default='', max_length=100),
        ),
    ]
