# Generated by Django 4.0.6 on 2022-07-24 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0001_initial'),
        ('app_user', '0002_appuser_ec_status_appuser_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_first_name', models.TextField(default='', null=True)),
                ('card_last_name', models.CharField(default='', max_length=2000)),
                ('card_phone_no', models.CharField(default='', max_length=100)),
                ('card_email', models.CharField(default='', max_length=2000)),
                ('card_profile_photo', models.FileField(blank=True, default='default_files/default_face.jpg', upload_to='account_files/profile_photos/')),
                ('card_website', models.CharField(default='', max_length=1000)),
                ('card_job_title', models.CharField(default='', max_length=1000)),
                ('card_company', models.CharField(default='', max_length=30, null=True)),
                ('card_address', models.CharField(default='', max_length=30, null=True)),
                ('card_city', models.CharField(default='', max_length=30, null=True)),
                ('card_state', models.CharField(default='', max_length=30, null=True)),
                ('card_zip_code', models.CharField(default='', max_length=30, null=True)),
                ('card_country', models.CharField(default='', max_length=30, null=True)),
                ('facebook_link', models.CharField(default='', max_length=30, null=True)),
                ('twitter_link', models.CharField(default='', max_length=30, null=True)),
                ('instagram_link', models.CharField(default='', max_length=30, null=True)),
                ('linkedin_link', models.CharField(default='', max_length=30, null=True)),
                ('app_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_user.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=5)),
                ('first_name', models.CharField(max_length=125)),
                ('last_name', models.CharField(max_length=125)),
                ('email', models.CharField(max_length=125)),
                ('phone', models.CharField(blank=True, max_length=125)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(blank=True, max_length=125)),
                ('state', models.CharField(blank=True, max_length=125)),
                ('postal_code', models.CharField(blank=True, max_length=125)),
                ('country', models.CharField(blank=True, max_length=125)),
                ('total', models.FloatField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Preapparing', 'Preapparing'), ('OnShipping', 'OnShipping'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=15)),
                ('adminnote', models.CharField(blank=True, max_length=125)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_user.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='ShopCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('app_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_user.appuser')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='card.card')),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryCardInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled')], default='New', max_length=15)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.card')),
                ('cardinfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cardinfo')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Cancelled', 'Cancelled')], default='New', max_length=15)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.appuser')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.card')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
