# Generated by Django 4.0.6 on 2022-07-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='primarycardinfo',
            name='app_user',
        ),
        migrations.RemoveField(
            model_name='primarycardinfo',
            name='card',
        ),
        migrations.RemoveField(
            model_name='primarycardinfo',
            name='cardinfo',
        ),
        migrations.AddField(
            model_name='order',
            name='card_address',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_city',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_company',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_country',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_email',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='order',
            name='card_first_name',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_job_title',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='card_last_name',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='order',
            name='card_phone_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='card_profile_photo',
            field=models.FileField(blank=True, default='default_files/default_face.jpg', upload_to='account_files/profile_photos/'),
        ),
        migrations.AddField(
            model_name='order',
            name='card_state',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_website',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='card_zip_code',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='facebook_link',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='instagram_link',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='linkedin_link',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='twitter_link',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='CardInfo',
        ),
        migrations.DeleteModel(
            name='PrimaryCardInfo',
        ),
    ]
