# Generated by Django 4.0.6 on 2022-07-25 01:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_primarycardinfo_app_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_first_name', models.TextField(default='', null=True)),
                ('card_last_name', models.CharField(default='', max_length=2000)),
                ('card_phone_no', models.CharField(default='', max_length=100)),
                ('card_email', models.CharField(default='', max_length=2000)),
                ('card_profile_photo', models.FileField(blank=True, default='default_files/default_face.jpg', upload_to='account_files/profile_photos/')),
                ('card_website', models.CharField(default='', max_length=1000)),
                ('card_job_title', models.CharField(default='', max_length=1000)),
                ('card_company', models.CharField(default='', max_length=30, null=True)),
                ('card_address', models.CharField(default='', max_length=30, null=True)),
                ('card_city', models.CharField(default='', max_length=30, null=True)),
                ('card_state', models.CharField(default='', max_length=30, null=True)),
                ('card_zip_code', models.CharField(default='', max_length=30, null=True)),
                ('card_country', models.CharField(default='', max_length=30, null=True)),
                ('facebook_link', models.CharField(default='', max_length=30, null=True)),
                ('twitter_link', models.CharField(default='', max_length=30, null=True)),
                ('instagram_link', models.CharField(default='', max_length=30, null=True)),
                ('linkedin_link', models.CharField(default='', max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_company',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_job_title',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_phone_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_profile_photo',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_website',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_zip_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='order',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='order',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='order',
            name='twitter_link',
        ),
        migrations.CreateModel(
            name='OrderConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('card_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cardinfo')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='orders',
            field=models.ManyToManyField(through='order.OrderConnector', to='order.order'),
        ),
    ]
