# Generated by Django 4.0.6 on 2022-07-25 01:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_cardinfo_remove_order_card_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_address', models.CharField(default='', max_length=30, null=True)),
                ('card_city', models.CharField(default='', max_length=30, null=True)),
                ('card_state', models.CharField(default='', max_length=30, null=True)),
                ('card_zip_code', models.CharField(default='', max_length=30, null=True)),
                ('card_country', models.CharField(default='', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LinkInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.CharField(default='', max_length=30, null=True)),
                ('twitter_link', models.CharField(default='', max_length=30, null=True)),
                ('instagram_link', models.CharField(default='', max_length=30, null=True)),
                ('linkedin_link', models.CharField(default='', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_first_name', models.TextField(default='', null=True)),
                ('card_last_name', models.CharField(default='', max_length=2000)),
                ('card_phone_no', models.CharField(default='', max_length=100)),
                ('card_email', models.CharField(default='', max_length=2000)),
                ('card_profile_photo', models.FileField(blank=True, default='default_files/default_face.jpg', upload_to='account_files/profile_photos/')),
                ('card_website', models.CharField(default='', max_length=1000)),
                ('card_job_title', models.CharField(default='', max_length=1000)),
                ('card_company', models.CharField(default='', max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cardinfo',
            name='card_address',
        ),
        migrations.RemoveField(
            model_name='cardinfo',
            name='card_city',
        ),
        migrations.RemoveField(
            model_name='cardinfo',
            name='card_company',
        ),
        migrations.RemoveField(
            model_name='cardinfo',
            name='card_country',
        ),
        migrations.RemoveField(
            model_name='cardinfo',
            name='card_email',
        ),
        migrations.RemoveField(
            model_name='cardinfo',
            name='card_first_name',
        ),
        migrations.RemoveField(
            model_name='cardinfo',
            name='card_job_title',
        ),
        migrations.RemoveField(
            model_name='cardinfo',
            name='card_last_name',
        ),
        migrations.RemoveField(
            model_name='cardinfo',
            name='card_phone_no',
        ),
        migrations.RemoveField(
            model_name='cardinfo',
            name='card_profile_photo',
        ),
        migrations.RemoveField(
            model_name='cardinfo',
            name='card_state',
        ),
        migrations.RemoveField(
            model_name='cardinfo',
            name='card_website',
        ),
        migrations.RemoveField(
            model_name='cardinfo',
            name='card_zip_code',
        ),
        migrations.RemoveField(
            model_name='cardinfo',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='cardinfo',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='cardinfo',
            name='linkedin_link',
        ),
        migrations.RemoveField(
            model_name='cardinfo',
            name='twitter_link',
        ),
        migrations.CreateModel(
            name='PrimaryInfoConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('card_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cardinfo')),
                ('primary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.primaryinfo')),
            ],
        ),
        migrations.CreateModel(
            name='LinkInfoConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('card_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cardinfo')),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.linkinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AddressInfoConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.addressinfo')),
                ('card_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.cardinfo')),
            ],
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='addresses',
            field=models.ManyToManyField(through='order.AddressInfoConnector', to='order.addressinfo'),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='links',
            field=models.ManyToManyField(through='order.LinkInfoConnector', to='order.linkinfo'),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='primarys',
            field=models.ManyToManyField(through='order.PrimaryInfoConnector', to='order.primaryinfo'),
        ),
    ]
