# Generated by Django 4.0.6 on 2022-07-25 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_appuser_ec_status_appuser_status'),
        ('order', '0004_addressinfo_linkinfo_primaryinfo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressinfoconnector',
            name='address',
        ),
        migrations.RemoveField(
            model_name='addressinfoconnector',
            name='card_info',
        ),
        migrations.RemoveField(
            model_name='linkinfoconnector',
            name='card_info',
        ),
        migrations.RemoveField(
            model_name='linkinfoconnector',
            name='link',
        ),
        migrations.RemoveField(
            model_name='orderconnector',
            name='card_info',
        ),
        migrations.RemoveField(
            model_name='orderconnector',
            name='order',
        ),
        migrations.RemoveField(
            model_name='primaryinfoconnector',
            name='card_info',
        ),
        migrations.RemoveField(
            model_name='primaryinfoconnector',
            name='primary',
        ),
        migrations.RemoveField(
            model_name='cardinfo',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='cardinfo',
            name='links',
        ),
        migrations.RemoveField(
            model_name='cardinfo',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='cardinfo',
            name='primarys',
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='app_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_user.appuser'),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='card_address',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='card_city',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='card_code',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='card_company',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='card_country',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='card_email',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='card_job_title',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='card_last_name',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='card_phone_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='card_profile_photo',
            field=models.FileField(blank=True, default='default_files/default_face.jpg', upload_to='account_files/profile_photos/'),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='card_state',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='card_website',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='card_zip_code',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='facebook_link',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='instagram_link',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='linkedin_link',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cardinfo',
            name='twitter_link',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='AddressInfo',
        ),
        migrations.DeleteModel(
            name='AddressInfoConnector',
        ),
        migrations.DeleteModel(
            name='LinkInfo',
        ),
        migrations.DeleteModel(
            name='LinkInfoConnector',
        ),
        migrations.DeleteModel(
            name='OrderConnector',
        ),
        migrations.DeleteModel(
            name='PrimaryInfo',
        ),
        migrations.DeleteModel(
            name='PrimaryInfoConnector',
        ),
    ]
