# Generated by Django 4.0.6 on 2022-07-25 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_addressinfoconnector_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardinfo',
            name='card_first_name',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
